# Generated by Django 5.0.4 on 2024-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default='...', max_length=250),
        ),
    ]
