# Generated by Django 5.0.4 on 2024-05-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0007_products_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='newprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='promo',
            field=models.BooleanField(default=1),
        ),
    ]
