# Generated by Django 5.0.4 on 2024-05-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0008_brands_products_newprice_products_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backapi.brands'),
        ),
    ]
