# Generated by Django 5.0.4 on 2024-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0009_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
