# Generated by Django 5.0.4 on 2024-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0010_alter_products_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='promo',
            field=models.SmallIntegerField(default=2),
        ),
    ]
