# Generated by Django 5.0.4 on 2024-05-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0011_alter_products_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.SmallIntegerField(default=3),
        ),
    ]
