# Generated by Django 5.0.4 on 2024-05-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0012_products_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelivred', models.BooleanField(default=False)),
                ('isCommanded', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.users')),
            ],
        ),
    ]
