# Generated by Django 5.0.4 on 2024-05-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0014_alter_commandes_user_alter_products_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='img',
            new_name='imgg',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='name',
            new_name='namee',
        ),
    ]
