# Generated by Django 5.0.4 on 2024-05-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0015_rename_img_brands_imgg_rename_name_brands_namee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='imgg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='namee',
            new_name='name',
        ),
    ]
